### ISSUE TITLE
How do I access /home/web_user and how are save files stored

### ISSUE THREAD

**Issue by GRX** [Inglebard/dockerfiles#5]
Hi,

Thank you for the dockerfile! I have a nice setup right now only with a few issues that i'd like to solve;
- How do I access the `/home/web_user` directory that's showed when running retroarch?
- Where are save files stored? Saves seem to be deleted on a page refresh

Thank you in advance!

**Comment by Inglebard** [comment]
Hi @GRX ,

_How do I access the /home/web_user directory that's showed when running retroarch?_
You can't or not easily. You can only access through your web browser. You can use the web console and use the FS object to interact with files and folders. 
Example : FS.readdir("/home/web_user/retroarch/userdata/saves")
 
_Where are save files stored? Saves seem to be deleted on a page refresh_
Everything is stored in your web browser. So saves are deleted depending of your browser cache retention I suppose.

If you want to download/upload saves files you may use the web console and blob API (not tested).

You may have more information from the forum or official github repository.
