### ISSUE TITLE
ARM Build

### ISSUE THREAD

**Issue by Flowrome** [Inglebard/dockerfiles#6]
Hi 

I’d like to use your docker file to install retrarch web on my raspberry PI, but i’d need an ARM compatible image, do you know how to get one?

Thank you i really appreciate your work

**Comment by Inglebard** [comment]
I never build for arm.
I just updated my github actions for amd64, arm64 and arm7.

I am not able to test right now.
Can you test and tell me if it works properly ?

If it works I will also update retroarch-web-nightly.

**Comment by Flowrome** [comment]
I'll test it on a raspberry pi 4 with 8gb of ram running ubuntu 20.04, i'll comment back whenever i have the result, in the main time thank you!

**Comment by Flowrome** [comment]
Hi @Inglebard 

I’ve execute the action and everything seems to work fine, if you want to test it i’ve published this repo on docker just for testing purposes (i’ll take it down as soon after you’ll be able to publish your one) 
https://hub.docker.com/r/flowrome/retroarch-arm-web

Thank you for your hard work 👍 

Have a great day

**Comment by Inglebard** [comment]
Sorry, I think we misunderstood.

I update the action on my repository, it was not necessary to upload a new image (or maybe you want to maintain your own).

On your raspberry you can use directly inglebard/retroarch-web (on PC or raspberry).

**Comment by Flowrome** [comment]
I’m sorry it was a mistake of mine,

I’ll delete the repository on docker hub 👍 
thank you
