### ISSUE TITLE
Flycast will not run.

### ISSUE THREAD

**Issue by shrinedogg** [Inglebard/dockerfiles#7]
Curious if there's any additional setup here I'm missing, but I have this container running in kubernetes with an intel iGPU for hw acceleration. The container will run other cores, but it just sits and spins indefinitely when selecting `Flycast`.

![image](https://user-images.githubusercontent.com/53411346/142949864-f8f50b58-f071-4a59-a386-b00317197802.png)

**Comment by Inglebard** [comment]
Hi,

Unfortunately, the core is listed but it is not present in the official build for emscripten version.
