### ISSUE TITLE
Volume mapping

### ISSUE THREAD

**Issue by samkasman** [Inglebard/dockerfiles#9]
I've tried volume mapping files in, I can see them if I `docker exec` into the container, but they don't show up in any of the RetroArch cores. Any insight would be appreciated.

**Comment by Inglebard** [comment]
Hi,

Please check https://github.com/Inglebard/dockerfiles/issues/2 
Retroarch interface use a virtual filesystem. So files/folders may not be visible in the Retroarch interface even if present in docker container.
